version: "3.1"
services: 
    nginx:
      image: nginx
      container_name: nginx
      privileged: true
      #restart: always
      ports:
        - "80:80"
      environment:
         TZ: Asia/Shanghai
      volumes:
       - ./conf/nginx.conf:/etc/nginx/nginx.conf
       - ./logs:/var/log/nginx
       - ./html:/usr/share/nginx/html 
      network_mode: "bridge"
