version: "3.1"
services: 
  elasticsearch:
       image: elasticsearch:7.6.2
       container_name: es7_01
       privileged: true
       environment:
          cluster.name: "lloveyou"
          discovery.type: "single-node"
       volumes:
         - ./data:/usr/share/elasticsearch/data
         - ./logs:/usr/share/elasticsearch/logs
         - ./config/es1.yml:/usr/share/elasticsearch/config/elasticsearch.yml
         - ./config/jvm.options:/usr/share/elasticsearch/config/jvm.options
         - ./plugins:/usr/share/elasticsearch/plugins
       ports:
         - 9200:9200
         - 9300:9300
  kibana:
      image: kibana:7.6.2
      container_name: kibana
      ports:
        - 5601:5601
      volumes:
        - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml:rw
