version: "3.1"
services: 
   rabbitmq:
      image: rabbitmq:3.8.9-management
      container_name: rabbitmq
      hostname: rabbitmq
      privileged: true 
      #restart: always
      ports:
        - "5672:5672"
        - "15672:15672"
      environment:
         RABBITMQ_DEFAULT_USER: root
         RABBITMQ_DEFAULT_PASS: guest
      volumes:
      - ./data:/var/lib/rabbitmq
      - ./config:/etc/rabbitmq
      - ./log:/var/log/rabbitmq 
      network_mode: "bridge"
