version: "3.1"
services: 
    mysql:
      image: mysql
      container_name: mysql
      #restart: always
      ports: 
         - "3306:3306"
      environment:
         TZ: Asia/Shanghai
         MYSQL_ROOT_PASSWORD: 123456
      volumes:
      - ./data:/var/lib/mysql
      - ./config:/etc/mysql/conf.d
      - ./log:/var/log/mysql
